baseURL: "https://lucaswarwar.github.io" 
title: Lucas Warwar
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: wp/
          weight: 2
        #- name: Work in Progress
        #  url: wp/
         # weight: 3
        - name: Home
          url: /
          weight: 1
         # url: data/
          #weight: 3 
        - name: CV
          url: CV_LucasWarwar-2.pdf
          weight: 4

params:
    description: "I am a PhD student in Economics at Stanford University. My research interests are in public and labor economics."
    author: Lucas
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Lucas Warwar
          subtitle: "I am a PhD student in Economics at Stanford University. My research covers topics in labor and public economics in developing countries.\n\n\nIn my free time, I run (a lot). From Brazil.\n\n\nFeel free to reach out to me at warwar@stanford.edu."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Lucas
          buttons:
            - name: Research
              url: papers/
            - name: Work in Progress
              url: wp/
            - name: CV
              url: cv.pdf
            #- name: Readings
             # url: readings/
            #- name: Tags
             # url: tags/
            #- name: Archive
             # url: archive/
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:warwar@stanford.edu
        - name: LinkedIn
          url: https://www.linkedin.com/in/lucas-warwar-b85125307/
        - name: GitHub
          url: https://github.com/lucaswarwar
        - name: Twitter
          url: https://twitter.com/LucasWarwar

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Lucas Warwar"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
